---
#################### Create groups ####################
- name: Create group
  group:
    # with_dict 内の > 各要素 > groups
    name: "{{ item.value.groups }}"
    state: present
  # users > vars > main.yaml
  with_dict: "{{ user_newusers }}"

#################### Create user ####################
- name: Create users
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    shell: /bin/bash
    home: "/home/{{ item.key }}"
    state: present
    groups: "{{ item.value.groups }}"
  with_dict: "{{ user_newusers }}"

#################### Register pub key ####################
- name: Distribute authorized key
  authorized_key:
    user: "{{ item.key }}"
    # lookup →  with_* の処理のためのプラグイン。
    # lookup('プラグイン名', 引数)として呼び出す
    # file →Ansible システムの外のファイルにアクセス
    key: "{{ lookup('files', '/home/ec2_user/.ssh/MyKey.pem') }}"
  with_dict: "{{ user_newusers }}"

#################### sudoers ####################
- name: Deploy sudoers files
  template:
