---
AWSTemplateFormatVersion: 2010-09-09
################### Mappings ###################
Mappings:
  ELBLogger:
    ap-northeast-1:
      ElbAccountId: '582318560864'
  ConfigLogger:
    ap-northeast-1:
      ConfigAccountId: '136442786451'
################### Resources ###################
Resources:
  CodeStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: shivaq-code-store
################### shivaq-logs
  LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: shivaq-logs
      LifecycleConfiguration:
        Rules:
        - Id: Delete10Day
          Status: Enabled
          ExpirationInDays: 10
      # S3 logging consts exceed free tier limit, so stop this
      # LoggingConfiguration:
      #   DestinationBucketName: shivaq-logs
      #   LogFilePrefix: s3Logs/
      # # Need LogDeliveryWrite for the bucket to receive s3 logs
      # AccessControl: LogDeliveryWrite
################### BucketPolicy
  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: LogBucket
      PolicyDocument:
        Id: LogBucketPolicy
        Statement:
############# for Config logs #############
        - Sid: Policy4ConfigBucketPermissionsCheck
          Effect: Allow
          Principal:
            Service: config.amazonaws.com
          Action:
          - s3:GetBucketAcl
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - !Ref LogBucket
        - Sid: Policy4ConfigBucketDelivery
          Effect: Allow
          Principal:
            Service: config.amazonaws.com
          Action:
          - s3:PutObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - !Ref LogBucket
              - "/Config"
              - "/AWSLogs/"
              # Can not use !FindInMap in Join scope
              - Fn::FindInMap:
                - ConfigLogger
                - Ref: AWS::Region
                - ConfigAccountId
              - "/Config/"
              - "*"
          Condition:
            StringEquals:
              s3:x-amz-acl:
                - "bucket-owner-full-control"
############# for CloudTrail logs #############
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action:
          - s3:GetBucketAcl
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - !Ref LogBucket
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action:
          - s3:PutObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - !Ref LogBucket
              - "/cloudtrail"
              - "/AWSLogs/"
              # Can not use !FindInMap in Join scope
              - Fn::FindInMap:
                - ConfigLogger
                - Ref: AWS::Region
                - ConfigAccountId
              - "*"
          Condition:
            StringEquals:
              s3:x-amz-acl:
                - "bucket-owner-full-control"
############# for ELB logs #############
        - Sid: WriteAccess
          Action:
          - s3:PutObject
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - !Ref LogBucket
              # ELB を作ったときに、自動生成させて、それを模倣することにする
              # - "/prefix name of ELB???/"
              - "/AWSLogs/"
              - !Ref AWS::AccountId
              - "/*"
# arn:aws:s3:::bucket/prefix/AWSLogs/aws-account-id/*
          Principal:
            AWS:
              - Fn::FindInMap:
                - ELBLogger
                - !Ref AWS::Region
                - ElbAccountId
################## LifeCycledSIABucket
# STANDARD_IA に 30日で移動
  # LifeCycledSIABucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: shivaq-lifecycled-standard-ia-bucket
  #     LifecycleConfiguration:
  #       Rules:
  #       - Id: Standard-IA-30days
  #         Status: Enabled
  #         Transitions:
  #         - StorageClass: STANDARD_IA
  #           TransitionInDays: 30
  #   DependsOn: LogGarbageBucket
################### LifeCycledGlacierBucket
# GLACIER に 10日で移動
#   LifeCycledGlacierBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: shivaq-lifecycled-glacier-bucket
#       LifecycleConfiguration:
#         Rules:
#         - Id: Glacier30days
#           Status: Enabled
#           Transitions:
#           - StorageClass: GLACIER
#             TransitionInDays: 90
################### LogGarbageBucket
# 失効日を指定
  # LogGarbageBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: shivaq-s3-log-bucket
  #     # S3 ログ格納先にするには必要
  #     AccessControl: LogDeliveryWrite
  #     LifecycleConfiguration:
  #       Rules:
  #       - Id: Delete1Day
  #         Status: Enabled
  #         ExpirationInDays: 1
